# Generated by Django 4.2.8 on 2024-06-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0004_excursion_favorite_delete_favoriteexcursion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
    ]
